### ISSUE TITLE
Error after upgrading to 1.0.4

### ISSUE THREAD

**Issue by dbrosy** [mabunixda/node-red-contrib-fronius-solar#31]
I get this error after upgrading:

"TypeError: fronius.GetPowerFlowRealtimeData is not a function"

I have restarted nodered

After looking at the changes to v1.0.4 i see the name of the function was changed but this function is defined in "node-fronius-solar" so it would also need to be changed there.

Needs to be called "GetPowerFlowRealtimeDataData"

**Comment by Fabi00815** [comment]
Is there any solution for this?

I cant get it downgraded to 1.0.3 and the 1.0.4 doenst run.

Help

**Comment by dbrosy** [comment]
Remove the node-red-contrib-fronius-solar from node-red 

From cli use node-red admin to install specific version 

then re-add nodes in your flow

**Comment by me6545445** [comment]
Same issue here.
When I enter "node-red-admin install node-red-contrib-fronius-solar-v1.0.3" it says "404: Module not found".
Can you give further instructions how to install version 1.0.3

**Comment by Znubbis** [comment]
Same here, 1.0.4 is broken. 
I'm not sure where Fronius updated the API but it did not help to update the inverter.

**Comment by tomy-d** [comment]
I do have the same issue .... updated to 1.0.4 ... getting error: "TypeError: fronius.GetPowerFlowRealtimeData is not a function"

**Comment by dbrosy** [comment]
for those with issue using 1.0.4 you will need to downgrade to 1.0.3

Install:

Command line:

`npm i node-red-contrib-fronius-solar@1.0.3`

Web Interface:

Go to `Settings | Pallete | Install` and click on `down arrow button` and paste following:

`https://registry.npmjs.org/node-red-contrib-fronius-solar/-/node-red-contrib-fronius-solar-1.0.3.tgz`

Note:
you may need to remove previous version before installing 1.0.3. If it is greyed than it is in use and you will need to remove any reference to it

**Comment by Fabi00815** [comment]
I wasnt able to downgrade so i did this quickfix for me:

`nano ./.node-red/node_modules/node-red-contrib-fronius-solar/fronius/fronius.js`

change line 83:
FROM:
      fronius.GetPowerFlowRealtimeData(node.options).then(function(json) { // eslint-disable-line
TO:
      fronius.GetPowerFlowRealtimeDataData(node.options).then(function(json) { // eslint-disable-line

save and restart node-red.

So i got the version 1.0.4 running.

**Comment by reitermarkus** [comment]
I also just updated my inverter and it also doesn't work with 1.0.4.

@tnn85 and @mabunixda, does 1.0.4 actually work for you? If yes, I assume not all inverters are updated to the same API version yet.

My inverter is a Symo 5.0-3-M at version 3.27.1-3.

**Comment by reitermarkus** [comment]
Okay, after looking into this more, the change makes no sense and cannot work.

The API call was always correctly called `GetPowerFlowRealtimeData`, nothing changed there. Only the function name in `node-fronius-solar` is wrong, see https://github.com/mwittig/node-fronius-solar/blob/0b782baa9cf3e059bcf9dd40487fa058823ae9a8/index.js#L153.

**Comment by reitermarkus** [comment]
Well, the same thing is actually already stated right in the issue text:

> After looking at the changes to v1.0.4 i see the name of the function was changed but this function is defined in "node-fronius-solar" so it would also need to be changed there.

Would probably make sense actually reading it next time. 😄

**Comment by tnn85** [comment]
@reitermarkus No, sorry. My changes didn't work and i was too lazy to look into it deeper.

**Comment by reitermarkus** [comment]
Right, so https://github.com/mabunixda/node-red-contrib-fronius-solar/pull/30 should be reverted until https://github.com/mwittig/node-fronius-solar/pull/13 is merged and released.

**Comment by Sigi100** [comment]
Hallo,
Ich habe den WR Fronius gen24.
Bei mir kommt seit dem Upgrade auf 1.0.4 auch die Fehlermeldung
"TypeError: fronius.GetPowerFlowRealtimeData ist keine Funktion"

Ich dachte zuerst es liegt am WR und habe diesen auch upgedatet.

Leider funktioniert es immer noch nicht.
Habe auch schon versucht den Node Inverter auf API Vers 1 umzustellen.
Springt aber immer wieder zurück auf Ver 0 ??

Echt Schade, war eine Super Node
Wir das vom Ersteller noch angepasst?

**Comment by mabunixda** [comment]
Ja ein Update kommt

**Comment by Sigi100** [comment]
Hallo mabunixda,

Super, vielen Dank.

Hatte es mittlerweile schon selbst gelöst mit der "http-request"-Node.
Anfrage an den WR.

Für Interessierte:

Node: http-Request: (Oder zum Test einfach in den Browser eingeben)

URL:    http://192.168.178.xxx/solar_api/v1/GetPowerFlowRealtimeData.fcgi?Scope=Device&DeviceId=0
- Nutzdaten ignorieren
- Rückgabe: Ein parsed JSON-Object.

Damit konnte ich die API Version 1 abfragen.

Es gibt auch noch andere Interessante Anfragen zu den einzelnen Werten der Strings,....

http://192.168.178.xxx/solar_api/GetAPIVersion.cgi

http://192.168.178.xxx/components/readable

http://192.168.178.xxx/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData

http://192.168.178.xxx/solar_api/v1/GetInverterRealtimeData.cgi

http://192.168.178.xxx/solar_api/v1/GetMeterRealtimeData.cgi?Scope=System
